package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println("=== Cloudflare DNS 管理测试示例 ===")
	fmt.Println()
	fmt.Println("本示例展示如何使用 cloudctl 管理 Cloudflare DNS 记录")
	fmt.Println()

	fmt.Println("## 前置条件")
	fmt.Println("1. 配置 Cloudflare API Token")
	fmt.Println("   export CLOUDFLARE_API_TOKEN=your-api-token")
	fmt.Println()
	fmt.Println("2. 确保已有至少一个 Zone")
	fmt.Println("   cloudctl cf zone list")
	fmt.Println()

	fmt.Println("## 测试命令")
	fmt.Println()

	fmt.Println("### 1. 列出 DNS 记录")
	fmt.Println("   cloudctl cf dns list example.com")
	fmt.Println("   cloudctl cf dns list example.com --type A")
	fmt.Println("   cloudctl cf dns list example.com -t CNAME")
	fmt.Println("   cloudctl cf dns list example.com -o json")
	fmt.Println()

	fmt.Println("### 2. 创建 DNS 记录")
	fmt.Println("   # 创建 A 记录")
	fmt.Println("   cloudctl cf dns create example.com -t A -n www --content 1.2.3.4")
	fmt.Println()
	fmt.Println("   # 创建 A 记录并启用代理")
	fmt.Println("   cloudctl cf dns create example.com -t A -n api --content 1.2.3.4 --proxied")
	fmt.Println()
	fmt.Println("   # 创建 CNAME 记录")
	fmt.Println("   cloudctl cf dns create example.com -t CNAME -n blog --content example.com")
	fmt.Println()
	fmt.Println("   # 创建记录并指定 TTL")
	fmt.Println("   cloudctl cf dns create example.com -t A -n test --content 1.2.3.4 --ttl 3600")
	fmt.Println()

	fmt.Println("### 3. 更新 DNS 记录")
	fmt.Println("   # 更新记录内容")
	fmt.Println("   cloudctl cf dns update example.com <record-id> --content 2.3.4.5")
	fmt.Println()
	fmt.Println("   # 更新 TTL")
	fmt.Println("   cloudctl cf dns update example.com <record-id> --ttl 7200")
	fmt.Println()
	fmt.Println("   # 启用代理")
	fmt.Println("   cloudctl cf dns update example.com <record-id> --proxied")
	fmt.Println()
	fmt.Println("   # 禁用代理")
	fmt.Println("   cloudctl cf dns update example.com <record-id> --no-proxied")
	fmt.Println()
	fmt.Println("   # 同时更新多个字段")
	fmt.Println("   cloudctl cf dns update example.com <record-id> --content 2.3.4.5 --ttl 3600 --proxied")
	fmt.Println()

	fmt.Println("### 4. 删除 DNS 记录")
	fmt.Println("   cloudctl cf dns delete example.com <record-id>")
	fmt.Println()

	fmt.Println("## 完整测试流程")
	fmt.Println()
	fmt.Println("1. 列出现有记录")
	fmt.Println("   cloudctl cf dns list example.com")
	fmt.Println()
	fmt.Println("2. 创建测试记录")
	fmt.Println("   cloudctl cf dns create example.com -t A -n test --content 1.2.3.4")
	fmt.Println()
	fmt.Println("3. 再次列出记录，确认创建成功")
	fmt.Println("   cloudctl cf dns list example.com --type A")
	fmt.Println()
	fmt.Println("4. 更新记录内容")
	fmt.Println("   cloudctl cf dns update example.com <record-id> --content 2.3.4.5")
	fmt.Println()
	fmt.Println("5. 查看更新后的记录")
	fmt.Println("   cloudctl cf dns list example.com --type A")
	fmt.Println()
	fmt.Println("6. 删除测试记录")
	fmt.Println("   cloudctl cf dns delete example.com <record-id>")
	fmt.Println()
	fmt.Println("7. 确认删除成功")
	fmt.Println("   cloudctl cf dns list example.com --type A")
	fmt.Println()

	fmt.Println("## 注意事项")
	fmt.Println("- 创建记录前请确保域名已添加到 Cloudflare")
	fmt.Println("- 删除操作需要手动确认，输入 'yes' 才会执行")
	fmt.Println("- 使用 -vv 或 -vvv 参数可以查看详细的 API 调用日志")
	fmt.Println("- 使用 -o json 可以输出 JSON 格式，方便脚本处理")
	fmt.Println()

	os.Exit(0)
}
